name: monstermash
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3234116598032415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040807'
    - '#fef1de'
    - '#8a9a73'
    - '#566a4e'
    - '#efb973'
  brandStrength: 0.75
  lightness: 0.3667295384220779
  saturation: 0.9580687291454524
  rhythmicContrast: 0.8070896724238992
purpose: []
