name: monstermash
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34cccd'
    - '#f2650b'
    - '#96df41'
    - '#a40b0d'
    - '#396300'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
