name: monstermash
favicon: null
layout_spectrum: 0.48458
typography_spectrum: 0.56426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040807'
    - '#fef1de'
    - '#8a9a73'
    - '#566a4e'
    - '#efb973'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
